pipeline {
    //agent any
    agent {
        label 'AGENT_1'
    } 
     options {
        ansiColor('xterm') // You can specify a color mapping, such as 'xterm' or 'xterm256'
    }
    
    stages {
        stage('init') { 
            steps {
                sh '''
                ls -l
                pwd
                cd 1.roboshop-vpc
                pwd
                terraform init
                '''
            }
        }
        stage('plan') { 
            steps {
                sh '''
                pwd
                cd 1.roboshop-vpc
                terraform plan
                '''
            }
        }
        stage('Manual Approval') {
            steps {
                input "Approve deployment to production?"
                sh '''
                pwd
                cd 1.roboshop-vpc
                '''
    }
}
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success{
            echo 'I will run when the job is success'
        }
        failure{
            echo 'I will run when the job is failure'
        }
}

}
    

