pipeline {
    //agent any
    agent {
        label 'AGENT_1'
    } 
    stages {
        stage('init') { 
            steps {
                sh '''
                ls -l
                pwd
                cd 1.roboshop-vpc
                pwd
                terraform init
                '''
            }
        }
        stage('plan') { 
            steps {
                sh '''
                terraform plan
                '''
            }
        }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success{
            echo 'I will run when the job is success'
        }
        failure{
            echo 'I will run when the job is failure'
        }
}


